### ISSUE TITLE
Allow stratifying by Type code

### ISSUE THREAD

**Issue by juliangruendner** [medizininformatik-initiative/fhir-data-evaluator#5]
IS:
The fhir data evaluator currently only supports stratifying by values of type `Coding`.

SHOULD:
The evaluator should also support stratifying by values of type `code`.

Example Measure for code (Unit for laboratory value)
```json
{
  "code": {
    "coding": [
      {
        "system": "http://fhir-evaluator/strat/system",
        "code": "loinc-code-and-unit"
      }
    ]
  },
  "component": [
    {
      "criteria": {
        "language": "text/fhirpath",
        "expression": "Observation.code.coding.where(system='http://loinc.org')"
      },
      "code": {
        "coding": [
          {
            "system": "http://fhir-evaluator/strat/system",
            "code": "loinc-code"
          }
        ]
      }
    },
    {
      "criteria": {
        "language": "text/fhirpath",
        "expression": "(Observation.value as Quantity).code"
      },
      "code": {
        "coding": [
          {
            "system": "http://fhir-evaluator/strat/system",
            "code": "observation-unit"
          }
        ]
      }
    }
  ]
}
```

**Comment by alexanderkiel** [comment]
Ich würde hier eher ein FHIRPath schreiben, der ein Coding inkl. des Systems der Quantity erzeugt. Wir können nicht wissen, dass das System UCUM ist. Außerdem würde sich dann für den Evaluator nichts ändern.

**Comment by juliangruendner** [comment]
after furhter discussion with @alexanderkiel we decided to allow code evaluation directly - => please implement as described in initial ticked
